### ISSUE TITLE
Is it possible to keep the tooltip always visible?

### ISSUE THREAD

**Issue by ogiansouza** [whoisandy/react-rangeslider#101] opened 2017-12-11 12:51 UTC

**Comment by zhrivodkin** [comment] 2018-02-07 11:22
probably duplicate of #88.

**Comment by edwardfxiao** [comment] 2018-11-18 06:39
@whoisandy Hi, this feature is totally a nice one to have, or expose the current handle position could help.

Please review pull request https://github.com/whoisandy/react-rangeslider/pull/133. Thank you.

**Closed as completed** 2019-01-10 11:32 UTC
